# HORIZON — Static analysis configuration
#
# Uses the recommended Flutter lint ruleset with additional strict rules
# for code quality, safety, and consistency.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # --- Enabled strictness rules ---
    always_declare_return_types: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    noop_primitive_operations: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_single_quotes: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    use_build_context_synchronously: true

    # --- Additional safety rules ---
    avoid_dynamic_calls: true
    avoid_slow_async_io: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    prefer_void_to_null: true
    throw_in_finally: true
    unnecessary_statements: true
    avoid_catches_without_on_clauses: false  # Too strict for current codebase

analyzer:
  errors:
    # Treat these as warnings rather than errors during migration
    avoid_print: warning
    prefer_single_quotes: info
